"""remove chroma_db from setting

Revision ID: 4dad8be5fd82
Revises: 
Create Date: 2025-12-01 22:43:55.136444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dad8be5fd82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version_public')
    op.drop_constraint(op.f('orders_client_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'clients', ['client_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('settings_client_id_fkey'), 'settings', type_='foreignkey')
    op.create_foreign_key(None, 'settings', 'clients', ['client_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_column('settings', 'chroma_db')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('chroma_db', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'settings', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('settings_client_id_fkey'), 'settings', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('orders_client_id_fkey'), 'orders', 'clients', ['client_id'], ['id'])
    op.create_table('alembic_version_public',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_public_pkc'))
    )
    # ### end Alembic commands ###
