"""public_add_settings

Revision ID: 5e34efc97233
Revises: 
Create Date: 2025-11-19 02:37:51.701536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e34efc97233'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('leave_types', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['public.clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_settings_client_id'), 'settings', ['client_id'], unique=True, schema='public')
    op.drop_constraint(op.f('orders_client_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'clients', ['client_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('orders_client_id_fkey'), 'orders', 'clients', ['client_id'], ['id'])
    op.drop_index(op.f('ix_public_settings_client_id'), table_name='settings', schema='public')
    op.drop_table('settings', schema='public')
    # ### end Alembic commands ###
