from .user import UserRepository
from .manager import ManagerRepository
from .recruiter import RecruiterRepository
from .employee import EmployeeRepository
from .applicant import ApplicantRepository
from .job import JobRepository
from .application import ApplicationRepository
from .ai_interview import AiInterviewRepository
from .leave_entitlement import LeaveEntitlementRepository
from .leave_request import LeaveRequestRepository