"""initial public schema

Revision ID: abc4bc2f6b9f
Revises: 
Create Date: 2026-05-23 21:53:34.873928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc4bc2f6b9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('plan_duration', sa.Enum('THREE_MONTHS', 'SIX_MONTHS', 'TWELVE_MONTHS', name='subscriptionplan'), nullable=True),
    sa.Column('plan_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_clients_email'), 'clients', ['email'], unique=True, schema='public')
    op.create_index(op.f('ix_public_clients_tenant_id'), 'clients', ['tenant_id'], unique=True, schema='public')
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=255), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=512), nullable=True),
    sa.Column('plan', sa.Enum('THREE_MONTHS', 'SIX_MONTHS', 'TWELVE_MONTHS', name='subscriptionplan'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['public.clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_orders_razorpay_order_id'), 'orders', ['razorpay_order_id'], unique=True, schema='public')
    op.create_index(op.f('ix_public_orders_razorpay_payment_id'), 'orders', ['razorpay_payment_id'], unique=True, schema='public')
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('leave_types', sa.JSON(), nullable=True),
    sa.Column('policy_docs', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['public.clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_settings_client_id'), 'settings', ['client_id'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_settings_client_id'), table_name='settings', schema='public')
    op.drop_table('settings', schema='public')
    op.drop_index(op.f('ix_public_orders_razorpay_payment_id'), table_name='orders', schema='public')
    op.drop_index(op.f('ix_public_orders_razorpay_order_id'), table_name='orders', schema='public')
    op.drop_table('orders', schema='public')
    op.drop_index(op.f('ix_public_clients_tenant_id'), table_name='clients', schema='public')
    op.drop_index(op.f('ix_public_clients_email'), table_name='clients', schema='public')
    op.drop_table('clients', schema='public')
    # ### end Alembic commands ###
